### ISSUE TITLE
error in readme

### ISSUE THREAD

**Issue by Talasta** [42-AI/42ai_pdf_builder#7]
`<img src="{image_path}" width={image_width} height={image_height}>`
Should be replaced by :
`<img src="image_path" />`

the `[ />]` is mandatoy at the end of the html tag to work...

**Comment by matboivin** [comment]
Added `/>` in commit https://github.com/42-AI/42ai_pdf_builder/pull/5/commits/e9101cd0ddb3e323d2b9aac6788d95f5a48b3072

**Comment by Talasta** [comment]
Yes

**Comment by matboivin** [comment]
Changes have been merged into `dev`.

**Comment by matboivin** [comment]
Changes have been merged into `master`.
